import { v4 as uuid } from "uuid";

export const productDemo = [
  {
    _id: uuid(),
    name: "Areca Palm",
    price: 2499,
    rating: 5.0,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/vB3zSQxZ/Areca-palm.jpg",
  },
  {
    _id: uuid(),
    name: "Broken Heart",
    price: 179,
    rating: 4.8,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/mD9s45RM/Broken-Heart.jpg",
  },
  {
    _id: uuid(),
    name: "Fittonia Green",
    price: 190,
    rating: 4.8,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/L4qT9FrG/Fitonia-green.jpg",
  },
  {
    _id: uuid(),
    name: "Monstera Deliciosa",
    price: 1169,
    rating: 4.5,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/MpGXwqLQ/Monstera-Deliciosa.jpg",
  },
  {
    _id: uuid(),
    name: "Peperomia Green",
    price: 200,
    rating: 4.7,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/D0y3GyLQ/Peperomia-Green.jpg",
  },
  {
    _id: uuid(),
    name: "Peperomia Green",
    price: 250,
    rating: 4.7,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/X74kwBZ6/Golden-snake-Plant.jpg",
  },
  {
    _id: uuid(),
    name: "Jade Plant",
    price: 160,
    rating: 4.7,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/hjCcpdSZ/Jade-Plant.jpg",
  },
  {
    _id: uuid(),
    name: "Snake Plant",
    price: 500,
    rating: 5.0,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/rm5Yp6H1/snake-plant.jpg",
  },
  {
    _id: uuid(),
    name: "Rubber Plant",
    price: 299,
    rating: 4.3,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/rmbFqrv0/Rubber-Plant.jpg",
  },
  {
    _id: uuid(),
    name: "Red Plant",
    price: 349,
    rating: 4.8,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/gJ4thyYj/Red-plant.jpg",
  },
  {
    _id: uuid(),
    name: "Bamboo Palm Plant",
    price: 269,
    rating: 5.0,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/KjRfgdqp/Bamboo-palm-plant.jpg",
  },
  {
    _id: uuid(),
    name: "Wandering Jew",
    price: 999,
    rating: 4.9,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/xCF3tRq4/Wandering-jew.jpg",
  },
  {
    _id: uuid(),
    name: "Peacock Plant",
    price: 599,
    rating: 4.8,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/6pWJsWMx/Peacock-Plant.jpg",
  },
  {
    _id: uuid(),
    name: "Snake Plant Green",
    price: 199,
    rating: 4.7,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/5NZYprgz/Snake-Plant-Green.jpg",
  },
  {
    _id: uuid(),
    name: "Ficus Plant",
    price: 1499,
    rating: 4.0,
    categoryName: "indoor",
    image_link: "https://i.postimg.cc/ZKVZ5vB5/Ficus.jpg",
  },
  {
    _id: uuid(),
    name: "Kesar Mango Plant",
    price: 949,
    rating: 3.5,
    categoryName: "fruit",
    image_link: "https://i.postimg.cc/HxTWLz16/Kesar-mango-plant.jpg",
  },
  {
    _id: uuid(),
    name: "Chiku Plant",
    price: 999,
    rating: 4.2,
    categoryName: "fruit",
    image_link: "https://i.postimg.cc/qRmrvdL7/Chiku-plant.jpg",
  },
  {
    _id: uuid(),
    name: "Anthurium Million Flowers",
    price: 599,
    rating: 4.8,
    categoryName: "flower",
    image_link: "https://i.postimg.cc/qRmrvdL7/Chiku-plant.jpg",
  },
  {
    _id: uuid(),
    name: "Poinsettia Plant",
    price: 799,
    rating: 4.7,
    categoryName: "flower",
    image_link: "https://i.postimg.cc/HnK4XJLJ/Poinsettia.jpg",
  },
  {
    _id: uuid(),
    name: "Rugmini Plant Red",
    price: 699,
    rating: 4.8,
    categoryName: "flower",
    image_link: "https://i.postimg.cc/Y0JYjJXY/Rugmini-plant-red.jpg",
  },
  {
    _id: uuid(),
    name: "The Dekstop Bundle",
    price: 1399,
    rating: 5.0,
    categoryName: "bundle",
    image_link: "https://i.postimg.cc/ht7zfyx1/The-Dekstop-bundle.png",
  },
  {
    _id: uuid(),
    name: "The Indoor Plant Bundle",
    price: 1299,
    rating: 4.9,
    categoryName: "bundle",
    image_link: "https://i.postimg.cc/y8Bx811s/The-indoor-plant-bundle.png",
  },
  {
    _id: uuid(),
    name: "The Low Maintainance Bundle",
    price: 1299,
    rating: 4.8,
    categoryName: "bundle",
    image_link: "https://i.postimg.cc/kXTzBw9G/The-low-maintainance-bundle.png",
  },
  {
    _id: uuid(),
    name: "The Sleep Better Bundle",
    price: 1299,
    rating: 4.7,
    categoryName: "bundle",
    image_link: "https://i.postimg.cc/zBM3zTBc/The-sleep-better-bundle.png",
  },
  {
    _id: uuid(),
    name: "The Sun Loving Bundle",
    price: 1499,
    rating: 5.0,
    categoryName: "bundle",
    image_link:
      "https://i.postimg.cc/xC73bsgG/The-sun-loving-succulent-bundle.png",
  },

  {
    _id: uuid(),
    name: "The Pack Of 4",
    price: 1199,
    rating: 5.0,
    categoryName: "pots",
    image_link: "https://i.postimg.cc/4NHFwc9N/Pack-of-4.png",
  },
  {
    _id: uuid(),
    name: "Football Ceramic Plant",
    price: 399,
    rating: 4.7,
    categoryName: "pots",
    image_link: "https://i.postimg.cc/XJ1Jxmyh/Football-ceramic.png",
  },
  {
    _id: uuid(),
    name: "Wooden Planter",
    price: 899,
    rating: 5.0,
    categoryName: "pots",
    image_link: "https://i.postimg.cc/ncXXCFQD/Wooden-Planter.jpg",
  },
  {
    _id: uuid(),
    name: "Self Watering",
    price: 1299,
    rating: 5.0,
    categoryName: "pots",
    image_link: "https://i.postimg.cc/brcqrPXQ/Self-watering.png",
  },
  {
    _id: uuid(),
    name: "Plastic Pots",
    price: 699,
    rating: 5.0,
    categoryName: "pots",
    image_link: "https://i.postimg.cc/kGnhfYK0/Plastic-pots.png",
  },
  {
    _id: uuid(),
    name: "Marigold Grow Kit",
    price: 1499,
    rating: 4.0,
    categoryName: "tool kit",
    image_link: "https://i.postimg.cc/g0yfKRfL/Marigoldkit.jpg",
  },
  {
    _id: uuid(),
    name: "Spinach Grow Kit",
    price: 1499,
    rating: 5.0,
    categoryName: "tool kit",
    image_link: "https://i.postimg.cc/mrdKqRgT/spinachkit.jpg",
  },
  {
    _id: uuid(),
    name: "Thyme Grow Kit",
    price: 799,
    rating: 4.0,
    categoryName: "tool kit",
    image_link: "https://i.postimg.cc/zXtWVcvV/Thyme1.jpg",
  },
  {
    _id: uuid(),
    name: "Cherry Tomato Grow Kit",
    price: 1399,
    rating: 5.0,
    categoryName: "tool kit",
    image_link: "https://i.postimg.cc/nhdJ8qd8/tomatokit.jpg",
  },
];
